#!/usr/bin/env python3
"""Generate crawlable category, brand, and product HTML plus sitemaps for kakobuyhunt.com."""
from __future__ import annotations

import json
import re
import shutil
from collections import defaultdict
from datetime import date
from html import escape
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = "https://kakobuyhunt.com"
MARKER = "generated by scripts/build_seo_pages.py"
AFF = "9v88f"
TODAY = date.today().isoformat()

ASSETS = """  <link rel="icon" href="/img/favicon.png" type="image/png" sizes="32x32" />
  <link rel="icon" href="/img/favicon.svg" type="image/svg+xml" />
  <link rel="apple-touch-icon" href="/img/apple-touch-icon.png" sizes="180x180" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Montserrat:wght@700;800&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/css/style.css" />
  <script src="/js/analytics.js"></script>"""

SCRIPTS = """  <script src="/js/i18n.js"></script>
  <script src="/js/data.js"></script>
  <script src="/js/catalog.js"></script>
  <script src="/js/slugs.js"></script>
  <script src="/js/ui.js"></script>
  <script src="/js/pages.js"></script>"""

CAT_LABELS = {
    "shoes": "Shoes",
    "jackets": "Jackets & Vests",
    "hoodies": "Hoodies & Sweaters",
    "t-shirts": "T-Shirts",
    "sets": "Tracksuits",
    "pants": "Pants",
    "shorts": "Shorts",
    "headwear": "Headwear",
    "bags": "Bags",
    "accessories": "Accessories",
    "jersey": "Jerseys",
    "watches": "Watches",
    "glasses": "Glasses",
    "underwear": "Underwear",
    "bricks": "Building Blocks",
    "perfume": "Perfume",
    "other": "Other Stuff",
}

CAT_INTRO = {
    "shoes": "Sneakers and shoes with USD prices, QC flags, and a working Kakobuy link on every card.",
    "jackets": "Jackets and vests from the Kakobuy Hunt spreadsheet — preview photos here, order on Kakobuy.",
    "hoodies": "Hoodies and sweaters with USD pricing and direct Kakobuy checkout links.",
    "t-shirts": "Tees and tops curated in Kakobuy Hunt. Open a card, then check out on Kakobuy.",
    "sets": "Tracksuits and matching sets priced in USD with Kakobuy links attached.",
    "pants": "Pants finds from the spreadsheet catalog — browse here, buy on Kakobuy.",
    "shorts": "Shorts with listing photos, USD prices, and Kakobuy links.",
    "headwear": "Caps, beanies and hats curated for Kakobuy shoppers.",
    "bags": "Bags and backpacks with USD prices and working Kakobuy links.",
    "accessories": "Belts, wallets, jewelry and small goods — preview here, order on Kakobuy.",
    "jersey": "Football, basketball and retro jerseys from the Kakobuy Hunt catalog.",
    "watches": "Watch finds with USD pricing and a Kakobuy link on every card.",
    "glasses": "Sunglasses and frames. Check photos here, then open Kakobuy.",
    "underwear": "Underwear and basics from the Kakobuy Hunt spreadsheet.",
    "bricks": "Building-block sets indexed for Kakobuy shoppers.",
    "perfume": "Fragrance listings from the Kakobuy Hunt catalog.",
    "other": "Finds outside a single apparel lane, still with photos and Kakobuy links.",
}

SKIP_BRAND = {"find", ""}


def load_products() -> list[dict]:
    raw = (ROOT / "js" / "catalog.js").read_text(encoding="utf-8")
    start = raw.index("KF.products = ") + len("KF.products = ")
    products, _ = json.JSONDecoder().raw_decode(raw[start:])
    return products


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower())
    s = re.sub(r"^-+|-+$", "", s)
    s = re.sub(r"-+", "-", s)
    return s[:60]


def item_id(p: dict) -> str:
    return re.sub(r"^p-", "", str(p.get("id") or ""), count=1)


def item_slug(p: dict) -> str:
    base = slugify(str(p.get("title") or ""))
    num = item_id(p)
    return f"{base}-{num}" if base else num


def asset(path: str) -> str:
    s = path or ""
    if not s or s.startswith("http") or s.startswith("/"):
        return s
    return "/" + s.lstrip("./")


def abs_url(path: str) -> str:
    return ORIGIN + path


def kakobuy_url(source_url: str) -> str:
    url = source_url or ""
    weidian = re.search(r"itemID=(\d+)", url, re.I)
    if weidian or "weidian.com" in url.lower():
        if weidian:
            return (
                "https://www.kakobuy.com/item/details?url="
                f"https%3A%2F%2Fweidian.com%2Fitem.html%3FitemID%3D{weidian.group(1)}"
                f"&affcode={AFF}"
            )
    return f"https://www.kakobuy.com/item/details?url={quote(url, safe='')}&affcode={AFF}"


def wipe_generated(dir_path: Path) -> None:
    index = dir_path / "index.html"
    if index.exists() and MARKER in index.read_text(encoding="utf-8", errors="ignore"):
        shutil.rmtree(dir_path)


def head(title: str, description: str, canonical: str, extra: str = "") -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <!-- {MARKER} -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{escape(title)}</title>
  <meta name="description" content="{escape(description)}" />
  <meta name="robots" content="index, follow, max-image-preview:large" />
  <meta name="author" content="kakobuyhunt" />
  <link rel="canonical" href="{escape(canonical)}" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Kakobuy Hunt" />
  <meta property="og:title" content="{escape(title)}" />
  <meta property="og:description" content="{escape(description)}" />
  <meta property="og:url" content="{escape(canonical)}" />
  <meta property="og:image" content="{ORIGIN}/img/og.png" />
{extra}{ASSETS}
</head>
"""


def product_card(p: dict) -> str:
    return (
        f'<a class="product-card" href="/item/{item_slug(p)}/" data-id="{escape(str(p["id"]))}">'
        f'<span class="thumb"><img src="{escape(asset(p.get("image") or ""))}" alt="{escape(p.get("title") or "")}" '
        f'width="320" height="320" loading="lazy" decoding="async" /></span>'
        f'<span class="body"><h3>{escape(p.get("title") or "")}</h3>'
        f'<b class="price">${float(p.get("price") or 0):.2f}</b></span></a>'
    )


def write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")


def shop_page(
    title: str,
    description: str,
    canonical: str,
    h1: str,
    intro: str,
    items: list[dict],
    body_attrs: str,
) -> str:
    cards = "\n      ".join(product_card(p) for p in items[:48])
    return (
        head(title, description, canonical)
        + f"<body {body_attrs}>\n"
        + f"""  <main class="wrap catalog">
    <div class="catalog-intro">
      <h1 id="shop-title">{escape(h1)}</h1>
      <p class="lede">{escape(intro)}</p>
    </div>
    <div class="catalog-top">
      <p id="shop-count">Showing {min(48, len(items))} of {len(items)} results</p>
      <select id="sort" aria-label="Sort finds">
        <option value="latest">Default sorting</option>
        <option value="popular">Sort by popularity</option>
        <option value="price-asc">Sort by price: low to high</option>
        <option value="price-desc">Sort by price: high to low</option>
      </select>
    </div>
    <div class="product-grid" id="product-grid">
      {cards}
    </div>
    <nav class="pager" id="pager"></nav>
  </main>
{SCRIPTS}
</body>
</html>
"""
    )


def item_page(p: dict, related: list[dict]) -> str:
    slug = item_slug(p)
    path = f"/item/{slug}/"
    canonical = abs_url(path)
    title = f'{p.get("title") or "Find"} — Kakobuy Hunt'
    price = float(p.get("price") or 0)
    cat = str(p.get("category") or "other")
    label = CAT_LABELS.get(cat, cat)
    image = abs_url(asset(p.get("image") or "img/og.png"))
    brand = str(p.get("collection") or "Kakobuy Hunt")
    desc = (
        f'{p.get("title")} on Kakobuy Hunt. {label} find'
        f'{f" from {brand}" if brand and brand.lower() != "find" else ""}, '
        f"listed at ${price:.2f}. Preview photos here, then open Kakobuy to order."
    )
    buy = kakobuy_url(str(p.get("sourceUrl") or ""))
    qc = "QC photos available" if p.get("qc") else "Review warehouse QC on Kakobuy before shipping"
    ld = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": p.get("title"),
        "image": image,
        "description": desc,
        "brand": {"@type": "Brand", "name": brand},
        "offers": {
            "@type": "Offer",
            "price": f"{price:.2f}",
            "priceCurrency": "USD",
            "availability": "https://schema.org/InStock",
            "url": canonical,
        },
    }
    extra = f'  <script type="application/ld+json">{json.dumps(ld, ensure_ascii=False)}</script>\n'
    rel = "\n        ".join(product_card(r) for r in related[:8])
    img = asset(p.get("image") or "")
    return (
        head(title, desc, canonical, extra)
        + f'<body data-page="item" data-item-id="{escape(str(p["id"]))}" data-cat="{escape(cat)}">\n'
        + f"""  <main class="wrap item-page">
    <nav class="crumbs" id="crumbs">
      <a href="/">Home</a><span>/</span>
      <a href="/finds/">Shop</a><span>/</span>
      <a href="/{escape(cat)}/">{escape(label)}</a><span>/</span>
      <span>{escape(p.get("title") or "")}</span>
    </nav>
    <div class="item-layout">
      <div class="item-gallery">
        <div class="item-stage"><img id="item-main" src="{escape(img)}" alt="{escape(p.get("title") or "")}" /></div>
        <div class="item-thumbs" id="thumbs"></div>
      </div>
      <div class="item-copy">
        <h1 id="item-title">{escape(p.get("title") or "")}</h1>
        <div class="price" id="item-price">${price:.2f}</div>
        <p class="meta">{escape(qc)} · {escape(brand)}</p>
        <div class="item-actions">
          <a class="btn btn-solid" id="buy-link" href="{escape(buy)}" target="_blank" rel="noopener">View on Kakobuy →</a>
          <a class="btn btn-ghost" href="/finds/">Back to catalog</a>
        </div>
        <p class="note">{escape(desc)}</p>
      </div>
    </div>
    <div class="section-head related-head">
      <div><h2>More in {escape(label)}</h2></div>
      <a class="btn btn-ghost" href="/{escape(cat)}/">See all →</a>
    </div>
    <div class="product-grid" id="related-grid">{rel}</div>
  </main>
{SCRIPTS}
</body>
</html>
"""
    )


def sitemap_xml(urls: list[tuple[str, str, str]]) -> str:
    body = "\n".join(
        f"  <url><loc>{escape(loc)}</loc><lastmod>{lastmod}</lastmod><changefreq>{freq}</changefreq></url>"
        for loc, lastmod, freq in urls
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + body
        + "\n</urlset>\n"
    )


def main() -> None:
    products = load_products()
    by_cat: dict[str, list] = defaultdict(list)
    by_brand: dict[str, list] = defaultdict(list)
    for p in products:
        seen = set()
        for slug in [p.get("category"), *(p.get("categories") or [])]:
            if slug and slug not in seen:
                by_cat[str(slug)].append(p)
                seen.add(slug)
        brand = str(p.get("collection") or "").strip()
        if brand.lower() not in SKIP_BRAND:
            by_brand[brand].append(p)

    # include catalog-only categories that have items
    for slug in list(by_cat):
        if slug not in CAT_LABELS:
            CAT_LABELS[slug] = slug.replace("-", " ").title()

    reserved = {"img", "js", "css", "scripts", "item", "brands", "finds", "pl", "sitemaps"}
    for slug in list(CAT_LABELS):
        if slug in reserved:
            continue
        wipe_generated(ROOT / slug)
    wipe_generated(ROOT / "finds")
    wipe_generated(ROOT / "brands")
    item_root = ROOT / "item"
    if item_root.exists():
        shutil.rmtree(item_root)

    write(
        ROOT / "finds" / "index.html",
        shop_page(
            "All finds — Kakobuy Hunt Spreadsheet",
            f"Browse {len(products)} Kakobuy Hunt finds with USD prices, QC flags and direct Kakobuy links.",
            abs_url("/finds/"),
            "All Kakobuy Hunt finds",
            "The full catalog in one grid — priced in USD, each card opening on Kakobuy.",
            products,
            'data-page="shop"',
        ),
    )

    for slug, label in CAT_LABELS.items():
        if slug in reserved:
            continue
        items = by_cat.get(slug, [])
        if not items:
            continue
        intro = CAT_INTRO.get(slug, f"{label} finds on Kakobuy Hunt.")
        write(
            ROOT / slug / "index.html",
            shop_page(
                f"{label} — Kakobuy Hunt",
                f"Browse {len(items)} {label.lower()} finds on Kakobuy Hunt — USD prices and Kakobuy links.",
                abs_url(f"/{slug}/"),
                f"{label} on Kakobuy Hunt",
                intro,
                items,
                f'data-page="shop" data-cat="{slug}"',
            ),
        )

    brand_names = sorted(
        ((name, items) for name, items in by_brand.items() if len(items) >= 5),
        key=lambda kv: (-len(kv[1]), kv[0].lower()),
    )
    brand_cards = "\n      ".join(
        f'<a class="brand-vault-card" href="/brands/{slugify(name)}/"><strong>{escape(name)}</strong>'
        f"<span>{len(items)} finds</span></a>"
        for name, items in brand_names
    )
    write(
        ROOT / "brands" / "index.html",
        head(
            "Brands — Kakobuy Hunt Spreadsheet",
            "Browse Kakobuy Hunt finds by brand: Nike, Jordan, Chrome Hearts and more.",
            abs_url("/brands/"),
        )
        + f"""<body data-page="brands">
  <main class="wrap catalog">
    <div class="catalog-intro">
      <h1>Brands on Kakobuy Hunt</h1>
      <p class="lede">Jump into a brand grid. Every card still opens on Kakobuy.</p>
    </div>
    <div class="brand-vault" id="brand-cloud">{brand_cards}</div>
  </main>
{SCRIPTS}
</body>
</html>
""",
    )
    for name, items in brand_names:
        bslug = slugify(name)
        write(
            ROOT / "brands" / bslug / "index.html",
            shop_page(
                f"{name} — Kakobuy Hunt",
                f"Browse {len(items)} {name} finds on Kakobuy Hunt with USD prices and Kakobuy links.",
                abs_url(f"/brands/{bslug}/"),
                f"{name} on Kakobuy Hunt",
                f"{name} listings curated in the spreadsheet. Preview photos here, then order on Kakobuy.",
                items,
                f'data-page="shop" data-brand="{bslug}"',
            ),
        )

    related_map: dict = defaultdict(list)
    for p in products:
        related_map[p.get("category")].append(p)
    slugs = {}
    for p in products:
        slug = item_slug(p)
        slugs[str(p["id"])] = slug
        related = [x for x in related_map[p.get("category")] if x["id"] != p["id"]]
        write(ROOT / "item" / slug / "index.html", item_page(p, related))

    (ROOT / "js" / "slugs.js").write_text(
        "window.KF_SLUGS = " + json.dumps(slugs, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )

    active_cats = [s for s in CAT_LABELS if s not in reserved and by_cat.get(s)]
    page_urls = [
        (abs_url("/"), TODAY, "daily"),
        (abs_url("/finds/"), TODAY, "daily"),
        (abs_url("/brands/"), TODAY, "weekly"),
        (abs_url("/how-to-buy.html"), TODAY, "weekly"),
        (abs_url("/faq.html"), TODAY, "weekly"),
        (abs_url("/about.html"), TODAY, "monthly"),
        (abs_url("/contact.html"), TODAY, "monthly"),
    ]
    page_urls += [(abs_url(f"/{slug}/"), TODAY, "daily") for slug in active_cats]
    page_urls += [(abs_url(f"/brands/{slugify(name)}/"), TODAY, "weekly") for name, _ in brand_names]
    product_urls = [(abs_url(f"/item/{slug}/"), TODAY, "weekly") for slug in slugs.values()]
    all_urls = page_urls + product_urls

    # One flat sitemap — GSC often fails child fetches under /sitemaps/ on Workers.
    write(ROOT / "sitemap.xml", sitemap_xml(all_urls))
    write(ROOT / "sitemap-pages.xml", sitemap_xml(page_urls))

    sm_dir = ROOT / "sitemaps"
    if sm_dir.exists():
        shutil.rmtree(sm_dir)
    for stale in ("sitemap-index.xml",):
        p = ROOT / stale
        if p.exists():
            p.unlink()

    print(
        f"wrote {len(products)} item pages, {len(active_cats)} categories, "
        f"{len(brand_names)} brands, {len(all_urls)} URLs in sitemap.xml"
    )


if __name__ == "__main__":
    main()
